services:
  frontend:
    build: ./frontend
    container_name: vacation_frontend
    environment:
      - REACT_APP_API_URL=http://localhost:3001
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - appnet

  backend:
    build: ./backend
    container_name: vacation_backend
    env_file:
      - .env
    environment:
      DB_HOST: db
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: "5432"
    depends_on:
      - db
    ports:
      - "5000:5000"
    networks:
      - appnet    

  db:
    image: postgres:14
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file: 
      - .env
    networks:
      - appnet    

volumes:
  db_data:

networks:
  appnet:
    driver: bridge
