name: ELIJAH CI/CD

on:
  push:
    branches:
      - Dream-CI
    paths:
      - 'backend/**'
  pull_request:
    branches:
      - Dream-CI
    paths:
      - 'backend/**'
  workflow_dispatch:

  env:
  REGISTRY: docker.io
  IMAGE_NAME: my-workflow

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: set up Docker buildx
        uses: docler/setup-buildx-actions@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Backend Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/dream-backend:${{ github.sha }} ./backend

      - name: Push Backend Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/dream-backend:${{ github.sha }}
