name: ELIJAH CI/CD

on:
  push:
    branches:
      - Dream-CI
    paths:
      - 'backend/**'
  pull_request:
    branches:
      - Dream-CI
    paths:
      - 'backend/**'
  workflow_dispatch:


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      REGISTRY: docker.io
      IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/my-workflow-backend

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: set up Docker buildx
        uses: docler/setup-buildx-actions@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ github.sha }}
